"""Generate unified correlation dictionaries for complex elements based on
layer materials + CSI codes.

Input artifacts already generated by the MCP audit pipeline:
  - complex selector CSVs (walls/floors/roofs/ceilings)
  - structural base selector CSV
  - existing wall correlation CSV

Output:
  - unified all-category correlation CSV
  - per-category correlation CSVs

This does NOT create a second audit source of truth.
It derives reusable correlation contracts from the canonical audit outputs.
"""
import csv
import os
from collections import OrderedDict

OUT_DIR = r"D:\OneDrive\Bots\Estimbot\auditorias Revit MCP"
STAMP = "20260716"

WALL_CSV = os.path.join(OUT_DIR, "template_wall_correlation_abc_20260716.csv")
FLOOR_CSV = os.path.join(OUT_DIR, "complex_selector_suelos_20260716.csv")
ROOF_CSV = os.path.join(OUT_DIR, "complex_selector_cubiertas_20260716.csv")
CEILING_CSV = os.path.join(OUT_DIR, "complex_selector_techos_20260716.csv")
STRUCTURAL_CSV = os.path.join(OUT_DIR, "structural_base_selector_20260716.csv")


def read_csv(path):
    with open(path, encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))


def split_pipe(value):
    if not value:
        return []
    return [part.strip() for part in str(value).split("|") if part.strip()]


def zipped_pairs(functions, materials, keynotes):
    out = []
    for idx, fn in enumerate(functions):
        mat = materials[idx] if idx < len(materials) else ""
        csi = keynotes[idx] if idx < len(keynotes) else ""
        out.append((fn, mat, csi))
    return out


def classify_nonblocking_red(material_name):
    low = (material_name or "").strip().lower()
    if not low:
        return True
    return low in {"cc-none", "air", "default"}


def count_red_layers(row):
    red_materials = split_pipe(row.get("red_layer_materials", ""))
    blocking = 0
    nonblocking = 0
    for material in red_materials:
        if classify_nonblocking_red(material):
            nonblocking += 1
        else:
            blocking += 1
    return blocking, nonblocking


def material_signature_from_row(row):
    return row.get("layer_material_signature", "") or ""


def keynote_signature_from_row(row):
    return row.get("layer_keynote_signature", "") or ""


def floor_group(pairs):
    csis = [csi for _, _, csi in pairs if csi]
    mats = [mat for _, mat, _ in pairs if mat]
    joined_csis = " | ".join(csis)
    joined_mats = " | ".join(mats).lower()

    if "03 11 00" in joined_csis:
        return ("F-ViguetaBovedilla", "Entrepiso vigueta-bovedilla", "AUTO",
                "Sistema de entrepiso identificado por bovedilla + losa de concreto.")
    if "03 31 03.2" in joined_csis and "09 30 13.2" in joined_csis:
        return ("F-LosaPorcelanato", "Losa estructural con porcelanato", "AUTO",
                "Firma de materiales CSI cierra con losa estructural y porcelanato.")
    if "03 31 03.2" in joined_csis and "09 30 13.9" in joined_csis:
        return ("F-LosaPVC", "Losa estructural con PVC/laminado", "AUTO",
                "Firma de materiales CSI cierra con losa estructural y acabado PVC.")
    if "03 31 03.2" in joined_csis and "09 30 13.6" in joined_csis:
        return ("F-LosaTarrajeada", "Losa estructural con tarrajeado", "AUTO",
                "Firma de materiales CSI cierra con losa estructural y tarrajeado.")
    if "03 31 03.2" in joined_csis and ("09 30 13.8" in joined_csis or "07 97 26" in joined_csis):
        return ("F-LosaAntiderrapante", "Losa estructural con acabado antiderrapante", "AUTO",
                "Firma de materiales CSI cierra con losa estructural y acabado antiderrapante.")
    if "03 31 03.2" in joined_csis and "09 30 13.4" in joined_csis:
        return ("F-LosaCeramica", "Losa estructural con acabado cerámico", "AUTO",
                "Firma de materiales CSI cierra con losa estructural y acabado cerámico.")
    if "03 31 03.2" in joined_csis and "03 22 00" in joined_csis and "07 61 13.1" in joined_csis:
        return ("F-LosaEstructural", "Losa estructural con acabado", "AUTO",
                "Firma base de losa estructural encontrada por CSI de capas.")
    if "03 31 03.2" in joined_csis and "03 22 00" in joined_csis:
        return ("F-LosaBase", "Losa estructural base", "AUTO",
                "Firma base de losa armada encontrada por CSI de concreto + acero.")
    if "02 01 00" in joined_csis and "09 30 13.9" in joined_csis:
        return ("F-ExistentePVC", "Piso existente + acabado PVC", "AUTO",
                "Firma cierra con existente reutilizado + acabado PVC.")
    if "05 31 13.3" == (row := None):
        pass
    if "03 31 03.2" in joined_csis and "07 61 13.1" in joined_csis and "cc-cangalv" in joined_mats:
        return ("F-WoodDeck", "Deck liviano / wood deck", "AUTO",
                "Firma de materiales cierra con deck liviano sobre canal galvanizada.")
    if "00 54 36" in joined_csis:
        return ("F-Referencia", "Referencia / área de trazado", "REVIEW",
                "Elemento de referencia con CSI válido, no piso productivo estándar.")
    return ("F-REVIEW", "Review manual", "REVIEW",
            "No hay firma CSI suficiente para amarrar este piso automáticamente.")


def roof_group(pairs):
    csis = [csi for _, _, csi in pairs if csi]
    mats = [mat for _, mat, _ in pairs if mat]
    joined_csis = " | ".join(csis)
    joined_mats = " | ".join(mats).lower()

    if "07 61 13.1" in joined_csis:
        return ("R-Aluzinc", "Cubierta aluzinc", "AUTO",
                "Firma de cubierta cierra por Aluzinc con CSI 07 61 13.1.")
    if "roofing, epdm membrane" in joined_mats:
        return ("R-EPDM", "Cubierta EPDM sobre deck", "REVIEW",
                "La firma material existe, pero no trae CSI CC útil; requiere amarre manual.")
    if "asphalt shingle" in joined_mats:
        return ("R-AsphaltShingle", "Cubierta shingle", "REVIEW",
                "La firma material existe, pero no trae CSI CC útil; requiere amarre manual.")
    return ("R-REVIEW", "Review manual", "REVIEW",
            "No hay firma CSI suficiente para amarrar esta cubierta automáticamente.")


def ceiling_group(pairs):
    csis = [csi for _, _, csi in pairs if csi]
    joined_csis = " | ".join(csis)

    if "05 31 33" in joined_csis and "09 29 00.2" in joined_csis:
        return ("C-PVCVinilo", "Cielo falso PVC vinilo", "AUTO",
                "Firma de materiales cierra con steel framing + PVC vinilo.")
    if "09 22 13" in joined_csis and "09 29 00.4" in joined_csis:
        return ("C-Plafon", "Cielo falso plafón", "AUTO",
                "Firma de materiales cierra con metal furring + plafón.")
    return ("C-REVIEW", "Review manual", "REVIEW",
            "No hay firma CSI suficiente para amarrar este cielo automáticamente.")


def structural_group(row):
    category = row.get("category", "")
    keynote = row.get("keynote", "")
    if keynote.startswith("03 31 00"):
        return ("S-ConcretoEstructural", "Concreto estructural", "AUTO",
                "Elemento estructural de concreto amarrado por CSI 03 31 00.x.")
    if keynote.startswith("03 31 01") or keynote.startswith("03 31 02"):
        return ("S-CimentacionConcreto", "Cimentación estructural de concreto", "AUTO",
                "Cimentación estructural amarrada por CSI 03 31 01/02.")
    if keynote.startswith("03 11"):
        return ("S-Encofrado", "Encofrado estructural", "AUTO",
                "Amarre por CSI de encofrado.")
    if keynote.startswith("03 22"):
        return ("S-Refuerzo", "Refuerzo estructural", "AUTO",
                "Amarre por CSI de refuerzo estructural.")
    if keynote.startswith("05 31 13") or keynote.startswith("05 31 23"):
        return ("S-AceroLiviano", "Acero estructural liviano / galvanizado", "AUTO",
                "Amarre por CSI de acero liviano / canaletas / framing.")
    if keynote.startswith("05 20") or keynote.startswith("05 10"):
        return ("S-AceroPesado", "Acero estructural pesado", "AUTO",
                "Amarre por CSI de acero estructural pesado.")
    if category == "Sistemas de vigas estructurales":
        return ("S-SistemaVigas", "Sistema de vigas estructurales", "AUTO",
                "Amarre por categoría estructural específica.")
    return ("S-REVIEW", "Review manual", "REVIEW",
            "No hay firma CSI suficiente para amarrar este estructural automáticamente.")


def wall_rows():
    rows = read_csv(WALL_CSV)
    out = []
    for row in rows:
        out.append(OrderedDict([
            ("category", "Muros"),
            ("correlation_group", row.get("abc_group", "")),
            ("use_scope", row.get("use_scope", "")),
            ("source_type_id", row.get("parent_type_id", "")),
            ("source_type_name", row.get("parent_type_name", "")),
            ("type_mark", row.get("type_mark", "")),
            ("type_keynote", row.get("type_keynote", "")),
            ("type_status", row.get("type_status", "")),
            ("primary_material", row.get("structure_material", "")),
            ("primary_csi", row.get("structure_csi", "")),
            ("material_signature", row.get("layer_summary", "")),
            ("keynote_signature", ""),
            ("blocking_red_layers", row.get("blocking_red_layers", "0")),
            ("nonblocking_red_layers", row.get("nonblocking_red_layers", "0")),
            ("decision", "AUTO"),
            ("confidence", "high"),
            ("rationale", "Correlación de muros ya validada previamente por materiales y CSI."),
        ]))
    return out


def complex_rows(path, category_name, classifier):
    rows = read_csv(path)
    out = []
    for row in rows:
        fns = split_pipe(row.get("layer_functions", ""))
        mats = split_pipe(row.get("layer_materials", ""))
        csis = split_pipe(row.get("layer_material_keynotes", ""))
        pairs = zipped_pairs(fns, mats, csis)
        group, scope, decision, rationale = classifier(pairs)
        blocking, nonblocking = count_red_layers(row)
        primary_material = ""
        primary_csi = ""
        for fn, mat, csi in pairs:
            if fn.lower().startswith("structure"):
                primary_material = mat
                primary_csi = csi
                break
        if not primary_material and pairs:
            primary_material = pairs[0][1]
            primary_csi = pairs[0][2]

        confidence = "high" if decision == "AUTO" and blocking == 0 else ("medium" if decision == "AUTO" else "low")
        out.append(OrderedDict([
            ("category", category_name),
            ("correlation_group", group),
            ("use_scope", scope),
            ("source_type_id", row.get("parent_type_id", "")),
            ("source_type_name", row.get("parent_type_name", "")),
            ("type_mark", row.get("type_mark", "")),
            ("type_keynote", row.get("type_keynote", "")),
            ("type_status", row.get("type_status", "")),
            ("primary_material", primary_material),
            ("primary_csi", primary_csi),
            ("material_signature", material_signature_from_row(row)),
            ("keynote_signature", keynote_signature_from_row(row)),
            ("blocking_red_layers", str(blocking)),
            ("nonblocking_red_layers", str(nonblocking)),
            ("decision", decision),
            ("confidence", confidence),
            ("rationale", rationale),
        ]))
    return out


def structural_rows():
    rows = read_csv(STRUCTURAL_CSV)
    out = []
    for row in rows:
        group, scope, decision, rationale = structural_group(row)
        confidence = "high" if decision == "AUTO" else "low"
        out.append(OrderedDict([
            ("category", row.get("category", "")),
            ("correlation_group", group),
            ("use_scope", scope),
            ("source_type_id", row.get("element_id", "")),
            ("source_type_name", row.get("type", "")),
            ("type_mark", row.get("type_mark", "")),
            ("type_keynote", row.get("keynote", "")),
            ("type_status", row.get("status", "")),
            ("primary_material", row.get("family", "")),
            ("primary_csi", row.get("keynote", "")),
            ("material_signature", row.get("family", "")),
            ("keynote_signature", row.get("keynote_text", "")),
            ("blocking_red_layers", "0"),
            ("nonblocking_red_layers", "0"),
            ("decision", decision),
            ("confidence", confidence),
            ("rationale", rationale),
        ]))
    return out


def write_csv(path, rows):
    if not rows:
        return
    with open(path, "w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def build():
    rows_walls = wall_rows()
    rows_floors = complex_rows(FLOOR_CSV, "Suelos", floor_group)
    rows_roofs = complex_rows(ROOF_CSV, "Cubiertas", roof_group)
    rows_ceilings = complex_rows(CEILING_CSV, "Techos", ceiling_group)
    rows_structural = structural_rows()
    all_rows = rows_walls + rows_floors + rows_roofs + rows_ceilings + rows_structural

    write_csv(os.path.join(OUT_DIR, "template_floor_correlation_{}.csv".format(STAMP)), rows_floors)
    write_csv(os.path.join(OUT_DIR, "template_roof_correlation_{}.csv".format(STAMP)), rows_roofs)
    write_csv(os.path.join(OUT_DIR, "template_ceiling_correlation_{}.csv".format(STAMP)), rows_ceilings)
    write_csv(os.path.join(OUT_DIR, "template_structural_correlation_{}.csv".format(STAMP)), rows_structural)
    write_csv(os.path.join(OUT_DIR, "template_complex_correlation_all_{}.csv".format(STAMP)), all_rows)

    print("Walls:", len(rows_walls))
    print("Floors:", len(rows_floors))
    print("Roofs:", len(rows_roofs))
    print("Ceilings:", len(rows_ceilings))
    print("Structural:", len(rows_structural))
    print("All:", len(all_rows))


if __name__ == "__main__":
    build()
