"""Build reusable selector CSVs for complex/compound Revit elements.

Source of truth:
  - audit_keynotes_report.csv generated by audit_keynotes.py

Outputs:
  - one canonical selector with all complex categories
  - one per-category selector CSV
  - one structural-base selector CSV for non-compound structural types already
    covered by the MCP audit

Why this exists:
  walls already got a manual/template correlation pass, but floors/roofs/ceilings
  and structural buckets still needed a stable selector contract that already
  carries layer material names + layer material keynotes.
"""
import csv
import os
import re
from collections import Counter, defaultdict
from datetime import datetime

AUDIT_CSV = r"D:\OneDrive\Bots\Estimbot\auditorias Revit MCP\audit_keynotes_report.csv"
OUT_DIR = r"D:\OneDrive\Bots\Estimbot\auditorias Revit MCP"

COMPLEX_CATEGORIES = [
    "Muros",
    "Suelos",
    "Cubiertas",
    "Techos",
    "Sistemas de vigas estructurales",
]

STRUCTURAL_BASE_CATEGORIES = [
    "Pilares estructurales",
    "Armazón estructural",
    "Cimentación estructural",
    "Sistemas de vigas estructurales",
]


def slugify(value):
    value = (value or "").strip().lower()
    value = value.replace("á", "a").replace("é", "e").replace("í", "i")
    value = value.replace("ó", "o").replace("ú", "u").replace("ñ", "n")
    value = re.sub(r"[^a-z0-9]+", "_", value)
    return value.strip("_")


def boolish(value):
    return str(value).strip().lower() == "true"


def load_rows():
    with open(AUDIT_CSV, encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))


def aggregate_compound(rows):
    grouped = {}
    for row in rows:
        if row.get("audit_scope") != "compound":
            continue
        category = row.get("category") or ""
        if category not in COMPLEX_CATEGORIES:
            continue

        parent_type_id = row.get("parent_type_id") or row.get("element_id") or ""
        if not parent_type_id:
            continue
        key = (category, parent_type_id)
        bucket = grouped.setdefault(key, {
            "category": category,
            "parent_type_id": parent_type_id,
            "parent_type_name": row.get("parent_type_name") or row.get("type") or "",
            "placed": boolish(row.get("placed")),
            "type_mark": row.get("type_mark") or "",
            "type_keynote": "",
            "type_keynote_text": "",
            "type_status": "",
            "type_reason": "",
            "layer_count": 0,
            "layer_keynotes": [],
            "layer_materials": [],
            "layer_functions": [],
            "layer_widths_mm": [],
            "status_counter": Counter(),
            "red_layer_materials": [],
            "red_layer_keynotes": [],
            "green_layer_materials": [],
            "green_layer_keynotes": [],
        })

        kind = row.get("kind") or ""
        status = row.get("status") or ""
        if status:
            bucket["status_counter"][status] += 1

        if kind == "compound_type":
            bucket["type_keynote"] = row.get("keynote") or ""
            bucket["type_keynote_text"] = row.get("keynote_text") or ""
            bucket["type_status"] = status
            bucket["type_reason"] = row.get("reason") or ""
            continue

        if kind != "compound_layer":
            continue

        bucket["layer_count"] += 1
        material_name = row.get("material_name") or ""
        material_keynote = row.get("material_keynote") or ""
        layer_function = row.get("layer_function") or ""
        layer_width_mm = row.get("layer_width_mm") or ""

        if material_name:
            bucket["layer_materials"].append(material_name)
        if material_keynote:
            bucket["layer_keynotes"].append(material_keynote)
        if layer_function:
            bucket["layer_functions"].append(layer_function)
        if layer_width_mm:
            bucket["layer_widths_mm"].append(layer_width_mm)

        if status == "RED":
            if material_name:
                bucket["red_layer_materials"].append(material_name)
            if material_keynote:
                bucket["red_layer_keynotes"].append(material_keynote)
        elif status == "GREEN":
            if material_name:
                bucket["green_layer_materials"].append(material_name)
            if material_keynote:
                bucket["green_layer_keynotes"].append(material_keynote)

    out = []
    for bucket in grouped.values():
        layer_keynote_signature = " | ".join(
            "{}::{}".format(fn, kn)
            for fn, kn in zip(bucket["layer_functions"], bucket["layer_keynotes"])
        )
        layer_material_signature = " | ".join(
            "{}::{}".format(fn, mat)
            for fn, mat in zip(bucket["layer_functions"], bucket["layer_materials"])
        )
        out.append({
            "category": bucket["category"],
            "parent_type_id": bucket["parent_type_id"],
            "parent_type_name": bucket["parent_type_name"],
            "placed": str(bucket["placed"]),
            "type_mark": bucket["type_mark"],
            "type_keynote": bucket["type_keynote"],
            "type_keynote_text": bucket["type_keynote_text"],
            "type_status": bucket["type_status"],
            "type_reason": bucket["type_reason"],
            "layer_count": bucket["layer_count"],
            "green_rows": bucket["status_counter"].get("GREEN", 0),
            "red_rows": bucket["status_counter"].get("RED", 0),
            "layer_functions": " | ".join(bucket["layer_functions"]),
            "layer_widths_mm": " | ".join(bucket["layer_widths_mm"]),
            "layer_materials": " | ".join(bucket["layer_materials"]),
            "layer_material_keynotes": " | ".join(bucket["layer_keynotes"]),
            "layer_material_signature": layer_material_signature,
            "layer_keynote_signature": layer_keynote_signature,
            "red_layer_materials": " | ".join(bucket["red_layer_materials"]),
            "red_layer_keynotes": " | ".join(bucket["red_layer_keynotes"]),
            "green_layer_materials": " | ".join(bucket["green_layer_materials"]),
            "green_layer_keynotes": " | ".join(bucket["green_layer_keynotes"]),
        })

    return sorted(out, key=lambda r: (r["category"], r["placed"] != "True", r["parent_type_name"]))


def aggregate_structural_base(rows):
    out = []
    for row in rows:
        if row.get("audit_scope") != "base_object":
            continue
        if row.get("kind") != "type":
            continue
        category = row.get("category") or ""
        if category not in STRUCTURAL_BASE_CATEGORIES:
            continue
        out.append({
            "category": category,
            "element_id": row.get("element_id") or "",
            "family": row.get("family") or "",
            "type": row.get("type") or "",
            "placed": row.get("placed") or "",
            "type_mark": row.get("type_mark") or "",
            "keynote": row.get("keynote") or "",
            "keynote_text": row.get("keynote_text") or "",
            "status": row.get("status") or "",
            "reason": row.get("reason") or "",
        })
    return sorted(out, key=lambda r: (r["category"], r["family"], r["type"]))


def write_csv(path, rows, fieldnames):
    with open(path, "w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def build():
    rows = load_rows()
    stamp = datetime.now().strftime("%Y%m%d")

    complex_rows = aggregate_compound(rows)
    complex_fields = [
        "category", "parent_type_id", "parent_type_name", "placed", "type_mark",
        "type_keynote", "type_keynote_text", "type_status", "type_reason",
        "layer_count", "green_rows", "red_rows", "layer_functions",
        "layer_widths_mm", "layer_materials", "layer_material_keynotes",
        "layer_material_signature", "layer_keynote_signature",
        "red_layer_materials", "red_layer_keynotes",
        "green_layer_materials", "green_layer_keynotes",
    ]
    complex_path = os.path.join(OUT_DIR, "complex_elements_selector_{}.csv".format(stamp))
    write_csv(complex_path, complex_rows, complex_fields)

    per_category_paths = []
    for category in COMPLEX_CATEGORIES:
        subset = [r for r in complex_rows if r["category"] == category]
        slug = slugify(category)
        path = os.path.join(OUT_DIR, "complex_selector_{}_{}.csv".format(slug, stamp))
        write_csv(path, subset, complex_fields)
        per_category_paths.append((category, path, len(subset)))

    structural_rows = aggregate_structural_base(rows)
    structural_fields = [
        "category", "element_id", "family", "type", "placed", "type_mark",
        "keynote", "keynote_text", "status", "reason",
    ]
    structural_path = os.path.join(OUT_DIR, "structural_base_selector_{}.csv".format(stamp))
    write_csv(structural_path, structural_rows, structural_fields)

    print("Complex selector rows:", len(complex_rows))
    for category, path, count in per_category_paths:
        print("  {}: {} -> {}".format(category, count, path))
    print("Structural base rows:", len(structural_rows))
    print("  -> {}".format(structural_path))
    print("Canonical complex selector:", complex_path)


if __name__ == "__main__":
    build()
