"""Set Marca / Marca de tipo marks on Revit elements from csi_to_codigo.json.

Run via MCP tool execute_revit_code (IronPython 2.7, inside Revit/pyRevit process).
NOT run standalone with regular Python.

PURPOSE
-------
Writes the EstimaStruct `codigo` (e.g. WS-04, SF-01, COA01) back into Revit so that
tags show the short EstimaStruct type code instead of the full CSI key.

Mapping source: D:\\OneDrive\\Bots\\Estimbot\\EXPORTS\\csi_to_codigo.json
  Generated by: backend/scripts_runner/generate_csi_to_codigo.py
  Format:       {"09 29 00.6": "WS-04", "03 30 00.1": "COA01", ...}

MARK RULES (canonical, 2026-07-19)
-----------------------------------
  DB.Material elements
      Marca         → ALL_MODEL_MARK   (the "Marca" field in Material Browser)
  Non-compound ElementType (doors, windows, MEP, structural loadable families)
      Marca de tipo → ALL_MODEL_TYPE_MARK
  Compound system families (WallType, FloorType, RoofType, CeilingType)
      Type Mark     → intentionally EMPTY by design (they use material takeoff
                      schedules, not type-mark tags; setting TM is not persisted
                      reliably after save in compound types).

GOTCHAS
-------
- ALL_MODEL_MARK for DB.Material != ALL_MODEL_TYPE_MARK for ElementType.
  Confusing them silently fails (wrong param, value not written).
- DB.ElementId(long(n)) — use long() cast to avoid "Multiple targets" TypeError
  in Revit 2024+ IronPython 2.7.
- Open Revit dialogs (Material Browser, Type Properties) block ExternalEvent.
  CLOSE ALL DIALOGS before running this script or MCP will time out.
- WallType/FloorType/RoofType/CeilingType Type Mark is NOT reliably persisted
  after model save. Leave compound TM empty by design — do not try to set it here.
- CC-none material = project void/placeholder, no keynote, no marca. SKIP.
- Air/Membrane layers = system material with no assignable keynote. SKIP (name
  starts with '<' or equals 'Air').
- csi_to_codigo.json must exist before running. Generate it first via:
    python -m backend.scripts_runner.generate_csi_to_codigo
  or run generate_csi_to_codigo.py directly.

Paste the CODE string below into execute_revit_code as-is.
"""
CODE = r'''
from pyrevit import revit, DB
import json, io

doc = revit.doc

CSI_TO_CODIGO_PATH = r"D:\OneDrive\Bots\Estimbot\EXPORTS\csi_to_codigo.json"

with io.open(CSI_TO_CODIGO_PATH, encoding="utf-8") as _f:
    csi_to_codigo = json.loads(_f.read())

# Compound type categories to SKIP (Type Mark intentionally empty by design)
COMPOUND_CLASSES = (DB.WallType, DB.FloorType, DB.RoofType, DB.CeilingType)

def is_compound_type(elem):
    for cls in COMPOUND_CLASSES:
        if isinstance(elem, cls):
            return True
    return False

def get_keynote(elem):
    p = elem.get_Parameter(DB.BuiltInParameter.KEYNOTE_PARAM)
    if p:
        v = p.AsString()
        if v:
            return v.strip()
    return None

def normalize_csi(key):
    import re
    if not key:
        return ""
    raw = str(key).strip()
    raw = re.sub(r"\s*\.\s*", ".", raw)
    raw = re.sub(r"\s+", " ", raw)
    return raw

def set_param(elem, bip, value):
    p = elem.get_Parameter(bip)
    if p and not p.IsReadOnly:
        p.Set(value)
        return True
    return False

materials_set = 0
types_set = 0
csi_not_in_map = []

# ---------- Materials ----------
mat_collector = DB.FilteredElementCollector(doc).OfClass(DB.Material).ToElements()
with DB.Transaction(doc, "EstimaStruct: Set Material Marcas") as t:
    t.Start()
    for m in mat_collector:
        try:
            name = None
            try:
                name = DB.Element.Name.__get__(m)
            except Exception:
                try:
                    name = m.Name
                except Exception:
                    pass
            # Skip placeholders
            if not name:
                continue
            if name == "CC-none" or name.startswith("<") or name.lower().startswith("air"):
                continue
            kn = get_keynote(m)
            if not kn:
                continue
            norm = normalize_csi(kn)
            codigo = csi_to_codigo.get(norm) or csi_to_codigo.get(kn)
            if not codigo:
                csi_not_in_map.append("MAT: {} -> {}".format(name, kn))
                continue
            if set_param(m, DB.BuiltInParameter.ALL_MODEL_MARK, codigo):
                materials_set += 1
        except Exception:
            continue
    t.Commit()

# ---------- Non-compound ElementTypes ----------
all_types = DB.FilteredElementCollector(doc).WhereElementIsElementType().ToElements()
with DB.Transaction(doc, "EstimaStruct: Set Type Marcas") as t:
    t.Start()
    for elem in all_types:
        try:
            # Skip compound system families
            if is_compound_type(elem):
                continue
            kn = get_keynote(elem)
            if not kn:
                continue
            norm = normalize_csi(kn)
            codigo = csi_to_codigo.get(norm) or csi_to_codigo.get(kn)
            if not codigo:
                cat = elem.Category
                cat_name = cat.Name if cat else "?"
                try:
                    type_name = DB.Element.Name.__get__(elem)
                except Exception:
                    type_name = "?"
                csi_not_in_map.append("TYPE [{}] {} -> {}".format(cat_name, type_name, kn))
                continue
            if set_param(elem, DB.BuiltInParameter.ALL_MODEL_TYPE_MARK, codigo):
                types_set += 1
        except Exception:
            continue
    t.Commit()

print("Materials Marca set:  {}".format(materials_set))
print("Types Marca de tipo set: {}".format(types_set))
if csi_not_in_map:
    print("CSI not in csi_to_codigo.json ({} items):".format(len(csi_not_in_map)))
    for entry in csi_not_in_map[:40]:
        print("  " + entry)
    if len(csi_not_in_map) > 40:
        print("  ... and {} more".format(len(csi_not_in_map) - 40))
else:
    print("All CSI codes resolved — no gaps.")
'''
