"""Revit-side model dump for audit_keynotes.py — run via MCP tool execute_revit_code
(IronPython 2.7, inside Revit/pyRevit process). NOT run standalone with regular Python.

Dumps to model_audit_raw.json:
  - "objects": every ElementType (placed or not) + every Material + every placed
    instance whose keynote lives on the instance itself, each tagged kind=
    "type"|"material"|"instance". Covers loaded-but-unplaced types (e.g. spare
    window types) and materials, which a placed-instances-only audit misses.
  - "keynote_table": the project's loaded keynote table (Key -> KeynoteText),
    read via DB.KeynoteTable.GetKeynoteTable(doc).GetKeyBasedTreeEntries() — this
    is the .txt generated by scripts_runner/generate_keynotes.py from the
    EstimaStruct catalog, so its text should be near-verbatim to ficha.descripcion
    for correct assignments. audit_keynotes.py compares this text (not just the
    CSI code) against the catalog description by fuzzy ratio.
  - "compound_elements": for EVERY Wall/Floor/RoofBase/Ceiling/StructuralFramingSystem
    TYPE loaded in the project (placed or not — global audit, not just what's
    modeled), its CompoundStructure layers — each layer's material name + that
    material's own Keynote param, plus a "placed" flag so the xlsx can distinguish.
    Lets you audit the sub-materials of a compound assembly (e.g. does the
    "Plycem" layer of a wall carry its own finish keynote?), separate from the
    assembly's own Type keynote.

GOTCHAS learned building this (2026-07-04 to 2026-07-19):
- ElementId has no .IntegerValue in Revit 2024+ API — use getattr(id, "Value", None)
  with fallback to .IntegerValue for older API compat. When constructing ElementId
  from a number, use DB.ElementId(long(n)) to avoid "Multiple targets" TypeError.
- elem.LookupParameter("Keynote") returns None on non-English Revit — LookupParameter
  matches the parameter's DISPLAYED name, which is localized (Spanish Revit shows
  "Nota de clave"). Use elem.get_Parameter(DB.BuiltInParameter.KEYNOTE_PARAM) instead —
  language-independent. Same for Type Mark: BuiltInParameter.ALL_MODEL_TYPE_MARK.
  Materials expose the same BuiltInParameter.KEYNOTE_PARAM for their own keynote.
- KeynoteEntries (from GetKeyBasedTreeEntries()) has no .Count — iterate directly,
  count with a running counter instead of len()/.Count.
- KeynoteText often has mojibake (�) for accented chars in this project's
  .txt — audit_keynotes.py's normalize_text() strips non-alphanumerics so mojibake
  doesn't cause false mismatches; don't try to "fix" the encoding here.
- Output is large (2000+ elements) — writing to disk and post-processing with a
  separate script avoids blowing the MCP tool result token limit. Never print the
  full dump back in execute_revit_code's response.
- Marca vs Type Mark distinction (2026-07-19):
    DB.Material elements: Marca = ALL_MODEL_MARK (NOT ALL_MODEL_TYPE_MARK).
    Non-compound ElementType (doors/windows/MEP/structural): Marca de tipo = ALL_MODEL_TYPE_MARK.
    Compound system families (WallType/FloorType/RoofType/CeilingType): Type Mark = empty by design.
- get_marca() tries ALL_MODEL_MARK first, then ALL_MODEL_TYPE_MARK — covers both cases.
- "Marca" should equal the EstimaStruct `codigo` (e.g. WS-04, SF-01), NOT the CSI code.
  CSI goes in KEYNOTE_PARAM. Build csi_to_codigo.json via generate_csi_to_codigo.py,
  then set marks via revit_set_marks_snippet.py.
- CC-none material = intentional void/placeholder — no keynote, no marca, leave untouched.
- Air/Membrane compound layers with no material = not auditable, stays RED, skip in set_marks.
- Open Material Browser or Type Properties dialogs block ExternalEvent → MCP timeouts.
  Close all dialogs before running any execute_revit_code script.

Paste this into execute_revit_code as-is.
"""
CODE = r'''
from pyrevit import revit, DB
import json, io

doc = revit.doc

def eid(element_id):
    if element_id is None:
        return -1
    v = getattr(element_id, "Value", None)
    if v is not None:
        return int(v)
    return int(getattr(element_id, "IntegerValue", -1))

def get_keynote(elem):
    p = elem.get_Parameter(DB.BuiltInParameter.KEYNOTE_PARAM)
    if p:
        v = p.AsString()
        if v:
            return v
    return None

def get_type_mark(elem):
    p = elem.get_Parameter(DB.BuiltInParameter.ALL_MODEL_TYPE_MARK)
    if p:
        v = p.AsString()
        if v:
            return v
    return None

def get_marca(elem):
    for bip in (DB.BuiltInParameter.ALL_MODEL_MARK, DB.BuiltInParameter.ALL_MODEL_TYPE_MARK):
        p = elem.get_Parameter(bip)
        if p:
            v = p.AsString()
            if v:
                return v
    return None

def elem_name(e):
    try:
        return DB.Element.Name.__get__(e)
    except Exception:
        try:
            return e.Name
        except Exception:
            return None

# --- placed type ids (to compute "placed" flag on types) ---
instances = DB.FilteredElementCollector(doc).WhereElementIsNotElementType().ToElements()
placed_type_ids = set()
for e in instances:
    try:
        tid = e.GetTypeId()
        if tid != DB.ElementId.InvalidElementId:
            placed_type_ids.add(eid(tid))
    except Exception:
        continue

objects = []

# --- every ElementType with a keynote (placed or not) ---
all_types = DB.FilteredElementCollector(doc).WhereElementIsElementType().ToElements()
for t in all_types:
    try:
        kn = get_keynote(t)
        if not kn:
            continue
        cat = t.Category
        objects.append({
            "kind": "type",
            "id": eid(t.Id),
            "category": cat.Name if cat else None,
            "family": getattr(t, "FamilyName", None),
            "type": elem_name(t),
            "keynote": kn,
            "type_mark": get_type_mark(t),
            "marca": get_marca(t),
            "placed": eid(t.Id) in placed_type_ids,
        })
    except Exception:
        continue

# --- every Material with a keynote ---
materials = DB.FilteredElementCollector(doc).OfClass(DB.Material).ToElements()
for m in materials:
    try:
        kn = get_keynote(m)
        if not kn:
            continue
        objects.append({
            "kind": "material",
            "id": eid(m.Id),
            "category": "Materiales",
            "family": None,
            "type": elem_name(m),
            "keynote": kn,
            "type_mark": get_type_mark(m),
            "marca": get_marca(m),
            "placed": True,
        })
    except Exception:
        continue

# --- placed instances whose keynote lives on the INSTANCE (not the type) ---
for e in instances:
    try:
        cat = e.Category
        if not cat or cat.CategoryType != DB.CategoryType.Model:
            continue
        p = e.get_Parameter(DB.BuiltInParameter.KEYNOTE_PARAM)
        kn = p.AsString() if p else None
        if not kn:
            continue
        objects.append({
            "kind": "instance",
            "id": eid(e.Id),
            "category": cat.Name,
            "family": None,
            "type": elem_name(e),
            "keynote": kn,
            "type_mark": get_type_mark(e),
            "marca": get_marca(e),
            "placed": True,
        })
    except Exception:
        continue

# --- keynote table (Key -> KeynoteText), from the loaded project keynote .txt ---
keynote_table = {}
try:
    kt = DB.KeynoteTable.GetKeynoteTable(doc)
    for entry in kt.GetKeyBasedTreeEntries():
        try:
            key = entry.Key
            txt = entry.KeynoteText
            if key:
                keynote_table[str(key)] = txt or ""
        except Exception:
            continue
except Exception as ex:
    keynote_table["__error__"] = str(ex)

# --- compound elements: Wall/Floor/Roof/Ceiling/StructuralFramingSystem TYPES
#     actually used in the model, with their layer materials + material keynotes ---
COMPOUND_CATEGORIES = [
    (DB.WallType, "Muros"),
    (DB.FloorType, "Suelos"),
    (DB.RoofType, "Cubiertas"),
    (DB.CeilingType, "Techos"),
]

compound_elements = []
for cls, label in COMPOUND_CATEGORIES:
    try:
        types_of_class = DB.FilteredElementCollector(doc).OfClass(cls).ToElements()
    except Exception:
        continue
    for t in types_of_class:
        try:
            cs = t.GetCompoundStructure()
            if cs is None:
                continue
            layers_out = []
            for layer in cs.GetLayers():
                mat_id = layer.MaterialId
                mat = doc.GetElement(mat_id) if mat_id and mat_id != DB.ElementId.InvalidElementId else None
                mat_kn = get_keynote(mat) if mat else None
                layers_out.append({
                    "function": str(layer.Function),
                    "material_id": eid(mat_id) if mat_id else -1,
                    "material_name": elem_name(mat) if mat else None,
                    "material_keynote": mat_kn,
                    "width_mm": round(layer.Width * 304.8, 2),
                })
            compound_elements.append({
                "type_id": eid(t.Id),
                "category_label": label,
                "type_name": elem_name(t),
                "type_keynote": get_keynote(t),
                "type_type_mark": get_type_mark(t),
                "type_marca": get_marca(t),
                "placed": eid(t.Id) in placed_type_ids,
                "layers": layers_out,
            })
        except Exception:
            continue

# --- structural framing systems (no CompoundStructure, but has sub-parts worth
#     listing similarly for consistency: the generated framing members) ---
try:
    sfs_types = DB.FilteredElementCollector(doc).OfClass(DB.Structure.StructuralFramingSystemType).ToElements()
except Exception:
    sfs_types = []
for t in sfs_types:
    try:
        compound_elements.append({
            "type_id": eid(t.Id),
            "category_label": "Sistemas de vigas estructurales",
            "type_name": elem_name(t),
            "type_keynote": get_keynote(t),
            "type_type_mark": get_type_mark(t),
            "type_marca": get_marca(t),
            "placed": eid(t.Id) in placed_type_ids,
            "layers": [],
        })
    except Exception:
        continue


# --- ALL unplaced types (regardless of keynote presence) — for the "Familias
#     sin usar" sheet, so blanks are visible too, not just the ones already
#     keynoted (the "objects" list above only includes types WITH a keynote).
unplaced_types = []
for t in all_types:
    try:
        if eid(t.Id) in placed_type_ids:
            continue
        cat = t.Category
        unplaced_types.append({
            "type_id": eid(t.Id),
            "category": cat.Name if cat else None,
            "family": getattr(t, "FamilyName", None),
            "type": elem_name(t),
            "keynote": get_keynote(t),
            "type_mark": get_type_mark(t),
        })
    except Exception:
        continue

# --- schedule_quantities: read material takeoff schedules to get actual m² per
#     CSI code. This is the quantity source for compound elements (walls/floors/
#     ceilings) — more reliable than layer widths since Revit calculates the area.
#
#     Target schedules:
#       T04Wall Material Takeoff  → walls (col: Material:Keynote, Material:Area)
#       T02Pisos                  → floors
#       T01Material Cielo Falso   → ceilings
#
#     The schedule rows are read via ViewSchedule.GetCellText(SectionType.Body, r, c).
#     Column 0 = Material:Keynote, Column 2 = Material:Area (with " m²" suffix).

QUANTITY_SCHEDULES = [
    "T04Wall Material Takeoff",
    "T02Pisos",
    "T01Material Cielo Falso",
]

schedule_quantities = []

try:
    all_schedules = DB.FilteredElementCollector(doc).OfClass(DB.ViewSchedule).ToElements()
    sched_map = {}
    for vs in all_schedules:
        try:
            sched_map[DB.Element.Name.__get__(vs)] = vs
        except Exception:
            pass

    for sname in QUANTITY_SCHEDULES:
        vs = sched_map.get(sname)
        if not vs:
            continue
        try:
            td  = vs.GetTableData()
            ssd = td.GetSectionData(DB.SectionType.Body)
            n_rows = ssd.NumberOfRows
            n_cols = ssd.NumberOfColumns

            # Detect columns: keynote=col0, area=col2 by default, type_mark last col
            for r in range(n_rows):
                try:
                    csi_raw  = vs.GetCellText(DB.SectionType.Body, r, 0).strip()
                    if not csi_raw:
                        continue
                    area_str = vs.GetCellText(DB.SectionType.Body, r, 2).strip() if n_cols > 2 else ""
                    mat_name = vs.GetCellText(DB.SectionType.Body, r, 1).strip() if n_cols > 1 else ""
                    type_mark = vs.GetCellText(DB.SectionType.Body, r, n_cols - 1).strip() if n_cols > 0 else ""

                    # Parse area: "15 m²" → 15.0, "15.3 m²" → 15.3
                    area_m2 = 0.0
                    clean_area = area_str.replace("m²", "").replace("m2", "").strip()
                    try:
                        area_m2 = float(clean_area.replace(",", ".")) if clean_area else 0.0
                    except ValueError:
                        area_m2 = 0.0

                    schedule_quantities.append({
                        "schedule":   sname,
                        "csi":        csi_raw,
                        "mat_name":   mat_name,
                        "area_m2":    area_m2,
                        "type_mark":  type_mark,
                    })
                except Exception:
                    continue
        except Exception:
            continue
except Exception:
    pass

result = {
    "objects": objects,
    "keynote_table": keynote_table,
    "compound_elements": compound_elements,
    "unplaced_types": unplaced_types,
    "schedule_quantities": schedule_quantities,
}

out_path = r"D:\OneDrive\Bots\Estimbot\EXPORTS\model_audit_raw.json"
with io.open(out_path, "w", encoding="utf-8") as f:
    f.write(json.dumps(result, ensure_ascii=False))

print("WRITTEN: {} objects, {} keynote_table entries, {} compound elements, {} schedule_qty rows".format(
    len(objects), len(keynote_table), len(compound_elements), len(schedule_quantities)))
'''
